### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by ChinmayGopal931** [nkrishang/tornado-cash-rebuilt#1]
Encountering failing tests when running tests for this project @nkrishang 

<img width="689" alt="Screenshot 2024-11-22 at 8 58 20 PM" src="https://github.com/user-attachments/assets/f0b6c16a-f6d2-4871-ad1e-97b354dcaf7b">

here is my package.json
```
{
  "name": "tornado-cash-reconstructed",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "circomlib": "^2.0.5",
    "circomlibjs": "^0.1.7",
    "ethers": "^6.13.4",
    "fixed-merkle-tree": "^0.7.3",
    "snarkjs": "^0.7.5"
  }
}

```

**Comment by 0xidli** [comment]
Experiencing the same issue. @nkrishang any ideas?

**Comment by nkrishang** [comment]
Hey @0xidli 👋🏽  thanks for sharing the issue, I just got to fixing this. I've described the problem / fix in the PR https://github.com/nkrishang/tornado-cash-rebuilt/pull/2

Closing this issue! Let me know if anything else pops up.
